// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protokulak.proto

/*
Package protokulak is a generated protocol buffer package.

It is generated from these files:
	protokulak.proto

It has these top-level messages:
	Oneof
	InitConnection
	ResultType
	AgentType
	ReturnType
*/
package protokulak

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Oneof struct {
	// Types that are valid to be assigned to Union:
	//	*Oneof_Init
	//	*Oneof_NewResult
	//	*Oneof_Agent
	//	*Oneof_Return
	Union isOneof_Union `protobuf_oneof:"union"`
}

func (m *Oneof) Reset()                    { *m = Oneof{} }
func (m *Oneof) String() string            { return proto.CompactTextString(m) }
func (*Oneof) ProtoMessage()               {}
func (*Oneof) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type isOneof_Union interface {
	isOneof_Union()
}

type Oneof_Init struct {
	Init *InitConnection `protobuf:"bytes,1,opt,name=init,oneof"`
}
type Oneof_NewResult struct {
	NewResult *ResultType `protobuf:"bytes,2,opt,name=newResult,oneof"`
}
type Oneof_Agent struct {
	Agent *AgentType `protobuf:"bytes,3,opt,name=agent,oneof"`
}
type Oneof_Return struct {
	Return *ReturnType `protobuf:"bytes,4,opt,name=return,oneof"`
}

func (*Oneof_Init) isOneof_Union()      {}
func (*Oneof_NewResult) isOneof_Union() {}
func (*Oneof_Agent) isOneof_Union()     {}
func (*Oneof_Return) isOneof_Union()    {}

func (m *Oneof) GetUnion() isOneof_Union {
	if m != nil {
		return m.Union
	}
	return nil
}

func (m *Oneof) GetInit() *InitConnection {
	if x, ok := m.GetUnion().(*Oneof_Init); ok {
		return x.Init
	}
	return nil
}

func (m *Oneof) GetNewResult() *ResultType {
	if x, ok := m.GetUnion().(*Oneof_NewResult); ok {
		return x.NewResult
	}
	return nil
}

func (m *Oneof) GetAgent() *AgentType {
	if x, ok := m.GetUnion().(*Oneof_Agent); ok {
		return x.Agent
	}
	return nil
}

func (m *Oneof) GetReturn() *ReturnType {
	if x, ok := m.GetUnion().(*Oneof_Return); ok {
		return x.Return
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Oneof) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Oneof_OneofMarshaler, _Oneof_OneofUnmarshaler, _Oneof_OneofSizer, []interface{}{
		(*Oneof_Init)(nil),
		(*Oneof_NewResult)(nil),
		(*Oneof_Agent)(nil),
		(*Oneof_Return)(nil),
	}
}

func _Oneof_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Oneof)
	// union
	switch x := m.Union.(type) {
	case *Oneof_Init:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Init); err != nil {
			return err
		}
	case *Oneof_NewResult:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.NewResult); err != nil {
			return err
		}
	case *Oneof_Agent:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Agent); err != nil {
			return err
		}
	case *Oneof_Return:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Return); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Oneof.Union has unexpected type %T", x)
	}
	return nil
}

func _Oneof_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Oneof)
	switch tag {
	case 1: // union.init
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(InitConnection)
		err := b.DecodeMessage(msg)
		m.Union = &Oneof_Init{msg}
		return true, err
	case 2: // union.newResult
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ResultType)
		err := b.DecodeMessage(msg)
		m.Union = &Oneof_NewResult{msg}
		return true, err
	case 3: // union.agent
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AgentType)
		err := b.DecodeMessage(msg)
		m.Union = &Oneof_Agent{msg}
		return true, err
	case 4: // union.return
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ReturnType)
		err := b.DecodeMessage(msg)
		m.Union = &Oneof_Return{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Oneof_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Oneof)
	// union
	switch x := m.Union.(type) {
	case *Oneof_Init:
		s := proto.Size(x.Init)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Oneof_NewResult:
		s := proto.Size(x.NewResult)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Oneof_Agent:
		s := proto.Size(x.Agent)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Oneof_Return:
		s := proto.Size(x.Return)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type InitConnection struct {
}

func (m *InitConnection) Reset()                    { *m = InitConnection{} }
func (m *InitConnection) String() string            { return proto.CompactTextString(m) }
func (*InitConnection) ProtoMessage()               {}
func (*InitConnection) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ResultType struct {
	TypeOfFunction string `protobuf:"bytes,1,opt,name=typeOfFunction" json:"typeOfFunction,omitempty"`
	AgentAmount    uint64 `protobuf:"varint,2,opt,name=agentAmount" json:"agentAmount,omitempty"`
	Code           string `protobuf:"bytes,3,opt,name=code" json:"code,omitempty"`
	Borders        string `protobuf:"bytes,4,opt,name=borders" json:"borders,omitempty"`
}

func (m *ResultType) Reset()                    { *m = ResultType{} }
func (m *ResultType) String() string            { return proto.CompactTextString(m) }
func (*ResultType) ProtoMessage()               {}
func (*ResultType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ResultType) GetTypeOfFunction() string {
	if m != nil {
		return m.TypeOfFunction
	}
	return ""
}

func (m *ResultType) GetAgentAmount() uint64 {
	if m != nil {
		return m.AgentAmount
	}
	return 0
}

func (m *ResultType) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ResultType) GetBorders() string {
	if m != nil {
		return m.Borders
	}
	return ""
}

type AgentType struct {
	X       float64 `protobuf:"fixed64,1,opt,name=x" json:"x,omitempty"`
	Y       float64 `protobuf:"fixed64,2,opt,name=y" json:"y,omitempty"`
	Fitness float64 `protobuf:"fixed64,3,opt,name=fitness" json:"fitness,omitempty"`
	Step    uint64  `protobuf:"varint,4,opt,name=step" json:"step,omitempty"`
	Best    bool    `protobuf:"varint,5,opt,name=best" json:"best,omitempty"`
}

func (m *AgentType) Reset()                    { *m = AgentType{} }
func (m *AgentType) String() string            { return proto.CompactTextString(m) }
func (*AgentType) ProtoMessage()               {}
func (*AgentType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AgentType) GetX() float64 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *AgentType) GetY() float64 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *AgentType) GetFitness() float64 {
	if m != nil {
		return m.Fitness
	}
	return 0
}

func (m *AgentType) GetStep() uint64 {
	if m != nil {
		return m.Step
	}
	return 0
}

func (m *AgentType) GetBest() bool {
	if m != nil {
		return m.Best
	}
	return false
}

type ReturnType struct {
	Good    bool   `protobuf:"varint,1,opt,name=good" json:"good,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
}

func (m *ReturnType) Reset()                    { *m = ReturnType{} }
func (m *ReturnType) String() string            { return proto.CompactTextString(m) }
func (*ReturnType) ProtoMessage()               {}
func (*ReturnType) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ReturnType) GetGood() bool {
	if m != nil {
		return m.Good
	}
	return false
}

func (m *ReturnType) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*Oneof)(nil), "protokulak.Oneof")
	proto.RegisterType((*InitConnection)(nil), "protokulak.InitConnection")
	proto.RegisterType((*ResultType)(nil), "protokulak.ResultType")
	proto.RegisterType((*AgentType)(nil), "protokulak.AgentType")
	proto.RegisterType((*ReturnType)(nil), "protokulak.ReturnType")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BHService service

type BHServiceClient interface {
	DoBHA(ctx context.Context, opts ...grpc.CallOption) (BHService_DoBHAClient, error)
}

type bHServiceClient struct {
	cc *grpc.ClientConn
}

func NewBHServiceClient(cc *grpc.ClientConn) BHServiceClient {
	return &bHServiceClient{cc}
}

func (c *bHServiceClient) DoBHA(ctx context.Context, opts ...grpc.CallOption) (BHService_DoBHAClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_BHService_serviceDesc.Streams[0], c.cc, "/protokulak.BHService/DoBHA", opts...)
	if err != nil {
		return nil, err
	}
	x := &bHServiceDoBHAClient{stream}
	return x, nil
}

type BHService_DoBHAClient interface {
	Send(*Oneof) error
	Recv() (*Oneof, error)
	grpc.ClientStream
}

type bHServiceDoBHAClient struct {
	grpc.ClientStream
}

func (x *bHServiceDoBHAClient) Send(m *Oneof) error {
	return x.ClientStream.SendMsg(m)
}

func (x *bHServiceDoBHAClient) Recv() (*Oneof, error) {
	m := new(Oneof)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for BHService service

type BHServiceServer interface {
	DoBHA(BHService_DoBHAServer) error
}

func RegisterBHServiceServer(s *grpc.Server, srv BHServiceServer) {
	s.RegisterService(&_BHService_serviceDesc, srv)
}

func _BHService_DoBHA_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BHServiceServer).DoBHA(&bHServiceDoBHAServer{stream})
}

type BHService_DoBHAServer interface {
	Send(*Oneof) error
	Recv() (*Oneof, error)
	grpc.ServerStream
}

type bHServiceDoBHAServer struct {
	grpc.ServerStream
}

func (x *bHServiceDoBHAServer) Send(m *Oneof) error {
	return x.ServerStream.SendMsg(m)
}

func (x *bHServiceDoBHAServer) Recv() (*Oneof, error) {
	m := new(Oneof)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _BHService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protokulak.BHService",
	HandlerType: (*BHServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DoBHA",
			Handler:       _BHService_DoBHA_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "protokulak.proto",
}

func init() { proto.RegisterFile("protokulak.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6f, 0xe2, 0x30,
	0x10, 0xc5, 0xbb, 0x09, 0xe0, 0x61, 0x85, 0x58, 0x4b, 0xbb, 0x8a, 0x38, 0xa1, 0x1c, 0x2a, 0x2e,
	0x45, 0x08, 0xa4, 0x1e, 0x7a, 0x2a, 0xb4, 0xaa, 0xd2, 0x13, 0x92, 0xdb, 0x3f, 0xc0, 0xc7, 0x80,
	0x2c, 0xc0, 0x8e, 0x62, 0xa7, 0x25, 0xf7, 0xfe, 0xcb, 0xfe, 0x99, 0xca, 0x03, 0x29, 0xe9, 0xc7,
	0x6d, 0xe6, 0xcd, 0x7b, 0xf3, 0xe6, 0x25, 0x86, 0x4e, 0x9a, 0x19, 0x67, 0xb6, 0xf9, 0x6e, 0xbe,
	0x1d, 0x50, 0x29, 0xe0, 0x8c, 0xc4, 0x6f, 0x0c, 0xc2, 0x99, 0x46, 0xb3, 0x16, 0x43, 0x08, 0x94,
	0x56, 0x2e, 0x62, 0x3d, 0xd6, 0x6f, 0x8d, 0xba, 0x83, 0x8a, 0xec, 0x41, 0x2b, 0x77, 0x6b, 0xb4,
	0xc6, 0xa5, 0x53, 0x46, 0x27, 0x35, 0x49, 0x4c, 0x71, 0x05, 0x5c, 0xe3, 0x8b, 0x44, 0x9b, 0xef,
	0x5c, 0xf4, 0x8b, 0x64, 0xff, 0xab, 0xb2, 0xe3, 0xe4, 0xa9, 0x48, 0x31, 0xa9, 0xc9, 0x33, 0x55,
	0x5c, 0x42, 0x38, 0xdf, 0xa0, 0x76, 0xd1, 0x6f, 0xd2, 0xfc, 0xab, 0x6a, 0x26, 0x7e, 0x70, 0x92,
	0x1c, 0x59, 0x62, 0x08, 0xf5, 0x0c, 0x5d, 0x9e, 0xe9, 0x28, 0xf8, 0xc9, 0xc3, 0x4f, 0x4e, 0x82,
	0x13, 0x6f, 0xda, 0x80, 0x30, 0xd7, 0xca, 0xe8, 0xb8, 0x03, 0xed, 0xcf, 0xb7, 0xc7, 0xaf, 0x0c,
	0xe0, 0x7c, 0x97, 0xb8, 0x80, 0xb6, 0x2b, 0x52, 0x9c, 0xad, 0xef, 0x73, 0x4d, 0x04, 0x8a, 0xcf,
	0xe5, 0x17, 0x54, 0xf4, 0xa0, 0x45, 0xc7, 0x4c, 0xf6, 0x26, 0xd7, 0xc7, 0xb0, 0x81, 0xac, 0x42,
	0x42, 0x40, 0xb0, 0x34, 0x2b, 0xa4, 0x4c, 0x5c, 0x52, 0x2d, 0x22, 0x68, 0x2c, 0x4c, 0xb6, 0xc2,
	0xcc, 0xd2, 0xe9, 0x5c, 0x96, 0x6d, 0xac, 0x80, 0x7f, 0x24, 0x15, 0x7f, 0x80, 0x1d, 0xc8, 0x97,
	0x49, 0x76, 0xf0, 0x5d, 0x41, 0x06, 0x4c, 0xb2, 0xc2, 0xaf, 0x58, 0x2b, 0xa7, 0xd1, 0x5a, 0xda,
	0xcc, 0x64, 0xd9, 0x7a, 0x43, 0xeb, 0x30, 0xa5, 0xcd, 0x81, 0xa4, 0xda, 0x63, 0x0b, 0xb4, 0x2e,
	0x0a, 0x7b, 0xac, 0xdf, 0x94, 0x54, 0xc7, 0xd7, 0x3e, 0x70, 0xf9, 0x91, 0x3c, 0x63, 0x63, 0xcc,
	0x8a, 0xec, 0x9a, 0x92, 0x6a, 0xef, 0xb1, 0x47, 0x6b, 0xe7, 0x1b, 0x24, 0x5f, 0x2e, 0xcb, 0x76,
	0x74, 0x03, 0x7c, 0x9a, 0x3c, 0x62, 0xf6, 0xac, 0x96, 0x28, 0xc6, 0x10, 0xde, 0x99, 0x69, 0x32,
	0x11, 0x7f, 0xab, 0x3f, 0x80, 0x1e, 0x4f, 0xf7, 0x3b, 0x14, 0xd7, 0xfa, 0x6c, 0xc8, 0x16, 0x75,
	0xc2, 0xc7, 0xef, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xeb, 0xc1, 0x92, 0x86, 0x02, 0x00, 0x00,
}
